export type Product = {
  slug: string;
  title: string;
  sku: string;
  price: string;
  priceMax: string;
  reviews: string;
  image: string;
  imageAlt: string;
  productType: string;
  tags: string[];
  publishedAt: string;
  imageCount: number;
  sizeCount: number;
  firstSizes: string[];
  lastSize: string;
  frameOptions: string[];
  styleLine: string;
  summary: string;
  bestFor: string;
  palette: string;
  texture: string;
  composition: string;
  roomGuide: string;
  sizeGuide: string;
  stylingTips: string[];
  highlights: string[];
};

export const sharedArtworkDetails = [
  "Made-to-order original wall art",
  "100% handmade on high-quality linen canvas",
  "Professional oil or acrylic paints",
  "Creation time is generally about 1 week; selected textured works may take 1-2 weeks",
  "Free global shipping, generally 3-7 days by FedEx/DHL after completion",
  "Rolled canvas ships in a hard paper tube; framed artwork ships in a wooden box",
  "Artist signature is placed on the back by default, with front signature available on request",
  "Custom sizing is available by email or WhatsApp",
];

export const products: Product[] = [
  {
    slug: "blue-green-minimalist-abstract-painting-bgm-009",
    title: "Blue & Green Minimalist Abstract Painting #BGM 009",
    sku: "BGM 009",
    price: "From $198.75",
    priceMax: "$2,910.00",
    reviews: "12 reviews",
    image: "/art/p01.jpg",
    imageAlt: "Vibrant Abstract Fish Movement Painting Wall Art for Modern Interiors #BGM 009",
    productType: "texture",
    tags: ["blue-green"],
    publishedAt: "2024-03-24",
    imageCount: 8,
    sizeCount: 16,
    firstSizes: ['18" X 24" ( 46 X 61cm )', '21" X 28" ( 53 X 71cm )', '24" X 32" ( 61 X 81cm )', '24" X 36" ( 60 X 90cm )'],
    lastSize: '50" X 100" ( 127 X 254cm )',
    frameOptions: ["Rolled Canvas", "Black Frame", "Gold Frame", "Silver Frame", "Wood Frame", "White Frame"],
    styleLine: "Blue-green minimalist texture painting with a lively fish-like movement.",
    summary: "BGM 009 is a blue and green minimalist abstract painting built for calm interiors that still need movement. The original product data identifies it as a handmade texture work with 16 size choices and rolled or framed finishing options.",
    bestFor: "Living rooms, bedrooms, hallways, spa-like interiors, and ocean-inspired modern spaces.",
    palette: "Layered blue, teal, green, and light neutral tones.",
    texture: "Visible handmade texture over linen canvas, using professional oil or acrylic paint.",
    composition: "A centered organic movement gives the piece a soft focal point without making the wall feel busy.",
    roomGuide: "Use it above a sofa, console, or bed when the room already has natural wood, white upholstery, linen, stone, or muted green accents.",
    sizeGuide: "Choose 18 x 24 or 21 x 28 inches for narrow walls; 30 x 40 inches and above work better over sofas and beds. The largest 50 x 100 inch format is suited to wide feature walls.",
    stylingTips: ["Pair with oak, walnut, linen, stone, and brushed nickel finishes.", "Choose a white or wood frame for an airy coastal look.", "Use black framing when the room has black window frames, lighting, or hardware."],
    highlights: ["Made-to-order", "16 size options", "6 finish options", "Free FedEx/DHL shipping"],
  },
  {
    slug: "beige-brown-minimalist-painting-bbm-002",
    title: "Beige & Brown Minimalist Painting #BBM 002",
    sku: "BBM 002",
    price: "From $386.25",
    priceMax: "$2,910.00",
    reviews: "13 reviews",
    image: "/art/p02.jpg",
    imageAlt: "Large Ocean Wave Minimalist Painting For Room Decor Wall Art #BBM 001",
    productType: "texture",
    tags: ["beige-brown"],
    publishedAt: "2024-04-16",
    imageCount: 6,
    sizeCount: 16,
    firstSizes: ['18" X 24" ( 46 X 61cm )', '21" X 28" ( 53 X 71cm )', '24" X 32" ( 61 X 81cm )', '24" X 36" ( 60 X 90cm )'],
    lastSize: '50" X 100" ( 127 X 254cm )',
    frameOptions: ["Black Frame", "Gold Frame", "Silver Frame", "Wood Frame", "White Frame"],
    styleLine: "Neutral beige-brown modern abstract wall decor for quiet, warm rooms.",
    summary: "BBM 002 is listed as large modern abstract wall decor for the living room. The original product data starts at framed pricing and offers 16 size choices with black, gold, silver, wood, or white frames.",
    bestFor: "Neutral living rooms, beige bedrooms, organic modern interiors, offices, and soft luxury spaces.",
    palette: "Warm beige, brown, cream, and muted earth tones.",
    texture: "Handmade oil or acrylic paint on linen canvas with framed presentation options.",
    composition: "The design reads like a soft wave or layered contour, giving neutral rooms a sculptural visual rhythm.",
    roomGuide: "This is strongest in rooms with boucle, travertine, cream walls, warm wood, brass accents, or taupe upholstery.",
    sizeGuide: "For a queen bed or apartment sofa, start around 30 x 40 or 36 x 48 inches. Use 40 x 80 or 50 x 100 inches when the artwork needs to anchor a long wall.",
    stylingTips: ["Select a gold frame for warmer interiors with brass lighting.", "Use a white frame when the room is minimal, bright, and gallery-like.", "Avoid placing it on a wall with nearly identical beige paint unless the frame provides contrast."],
    highlights: ["Made-to-order", "Framed finish choices", "16 size options", "Free global shipping"],
  },
  {
    slug: "blue-green-minimalist-abstract-painting-bgm-012",
    title: "Blue & Green Minimalist Abstract Painting #BGM 012",
    sku: "BGM 012",
    price: "From $198.75",
    priceMax: "$2,910.00",
    reviews: "8 reviews",
    image: "/art/p03.jpg",
    imageAlt: "Handcrafted Abstract Floral Canvas Art - Modern Acrylic Wall Decor #BGM 012",
    productType: "texture",
    tags: ["blue-green"],
    publishedAt: "2024-03-24",
    imageCount: 9,
    sizeCount: 16,
    firstSizes: ['18" X 24" ( 46 X 61cm )', '21" X 28" ( 53 X 71cm )', '24" X 32" ( 61 X 81cm )', '24" X 36" ( 60 X 90cm )'],
    lastSize: '50" X 100" ( 127 X 254cm )',
    frameOptions: ["Rolled Canvas", "Black Frame", "Gold Frame", "Silver Frame", "Wood Frame", "White Frame"],
    styleLine: "Modern acrylic floral abstraction in blue-green tones.",
    summary: "BGM 012 is a handcrafted abstract floral canvas artwork. Original product data shows nine product images, 16 sizes, and rolled canvas plus five framed finish choices.",
    bestFor: "Dining rooms, reading corners, serene bedrooms, and spaces that need color without harsh contrast.",
    palette: "Blue, green, white, and soft natural undertones.",
    texture: "Hand-painted texture with acrylic or oil paint over linen canvas.",
    composition: "The floral movement keeps the artwork organic while the blue-green palette keeps it contemporary.",
    roomGuide: "Use this piece when you want a nature reference that feels abstract rather than literal botanical art.",
    sizeGuide: "Use the smaller formats for side walls and the larger formats above low furniture. For rooms with high ceilings, choose a vertical or larger framed format from the available size list.",
    stylingTips: ["Works well near ceramic vases, soft green textiles, and pale oak.", "A white frame keeps the floral subject light; a black frame makes it feel more graphic.", "Place it where natural light can reveal texture, but avoid harsh direct sun."],
    highlights: ["9 source images", "Floral abstract subject", "Custom size available", "Rolled or framed"],
  },
  {
    slug: "blue-green-abstract-painting-cxa-017",
    title: "Blue & Green Abstract Painting #CXA 017",
    sku: "CXA 017",
    price: "From $198.75",
    priceMax: "$2,910.00",
    reviews: "30 reviews",
    image: "/art/p04.jpg",
    imageAlt: "Blue and Green Ocean Waves Gypsum Texture 3D Abstract Painting | Large Summer Living Room & Bedroom Wall Art Hanging Painting #CXA 017",
    productType: "texture",
    tags: ["blue-green"],
    publishedAt: "2023-12-28",
    imageCount: 9,
    sizeCount: 16,
    firstSizes: ['18" X 24" ( 46 X 61cm )', '21" X 28" ( 53 X 71cm )', '24" X 32" ( 61 X 81cm )', '24" X 36" ( 60 X 90cm )'],
    lastSize: '50" X 100" ( 127 X 254cm )',
    frameOptions: ["Rolled Canvas", "Black Frame", "Gold Frame", "Silver Frame", "Wood Frame", "White Frame"],
    styleLine: "3D ocean-wave abstract wall art for large summer rooms.",
    summary: "CXA 017 is described in the source alt text as a blue and green ocean wave gypsum texture 3D abstract painting for living rooms and bedrooms. It supports 16 sizes and six finish options.",
    bestFor: "Summer homes, coastal bedrooms, large living rooms, and modern spaces that need a cool statement piece.",
    palette: "Deep blue, green, white, and ocean-inspired highlights.",
    texture: "Raised 3D texture effect with handmade oil or acrylic surface work.",
    composition: "The wave motion creates a strong horizontal energy, making it especially useful above long furniture.",
    roomGuide: "Use it where a room needs movement: over a sectional, console, bed, or entry wall with clean surrounding decor.",
    sizeGuide: "For a wide sofa, consider 40 x 80 or 50 x 100 inches. Smaller formats are better as a single accent rather than the main room anchor.",
    stylingTips: ["Pair with white walls and dark blue or green accessories.", "Choose silver framing for cooler interiors and wood framing for a relaxed coastal feel.", "Leave breathing room around the artwork because the wave movement is visually active."],
    highlights: ["Ocean wave subject", "3D texture look", "16 size choices", "30 public review count"],
  },
  {
    slug: "textured-ocean-wave-art-3d-oil-painting-for-modern-home-decor-bbs-011",
    title: "Textured Ocean Wave Art 3D Oil Painting for Modern Home Decor #BBS 011",
    sku: "BBS 011",
    price: "From $261.25",
    priceMax: "$3,968.75",
    reviews: "3 reviews",
    image: "/art/p05.jpg",
    imageAlt: "Textured Ocean Wave Art 3D Oil Painting for Modern Home Decor #BBS 011",
    productType: "combine",
    tags: ["combine"],
    publishedAt: "2024-08-24",
    imageCount: 10,
    sizeCount: 15,
    firstSizes: ['2P 36" X 24"  ( Each 18" X 24" )', '2P 42" X 28"  ( Each 21" X 28" )', '2P 48" X 32"  ( Each 24" X 32" )', '2P 48" X 36"  ( Each 24" X 36" )'],
    lastSize: '2P 120" X 90"  ( Each 60" X 90" )',
    frameOptions: ["Rolled Canvas", "Black Frame", "Gold Frame", "Silver Frame", "Wood Frame", "White Frame"],
    styleLine: "Set-of-2 textured ocean wave oil painting for modern home decor.",
    summary: "BBS 011 is a two-piece textured ocean wave artwork. Original product data identifies it as a combine product with 15 paired sizes, 10 images, and a maximum set size of 2P 120 x 90 inches.",
    bestFor: "Large sofa walls, hotel-style bedrooms, dining rooms, entry halls, and coastal feature walls.",
    palette: "Blue, white, seafoam, and shadowed ocean tones.",
    texture: "3D oil painting texture across a diptych layout.",
    composition: "The two panels create a panoramic wave effect while allowing spacing between canvases for a custom wall width.",
    roomGuide: "Choose this when one canvas would feel too small or too static. The diptych format gives a long room more rhythm.",
    sizeGuide: "Measure the full pair width, not just each panel. Keep 2 to 5 inches between panels and aim for roughly two-thirds of the furniture width below.",
    stylingTips: ["Install both pieces level and keep the gap consistent.", "Use the larger paired sizes for sectional sofas or king beds.", "Let nearby decor stay simple so the 3D wave texture remains the focal point."],
    highlights: ["Set of 2", "15 paired sizes", "10 source images", "Highest price range in this selection"],
  },
  {
    slug: "blue-green-minimalist-abstract-painting-bgm-010",
    title: "Golden Blossom Tree Art - Textured Wall Decor #BGM 010",
    sku: "BGM 010",
    price: "From $198.75",
    priceMax: "$2,910.00",
    reviews: "17 reviews",
    image: "/art/p06.jpg",
    imageAlt: "Golden Blossom Tree Art - Textured Wall Decor, Modern Home Accent",
    productType: "texture",
    tags: ["blue-green"],
    publishedAt: "2024-03-24",
    imageCount: 6,
    sizeCount: 16,
    firstSizes: ['18" X 24" ( 46 X 61cm )', '21" X 28" ( 53 X 71cm )', '24" X 32" ( 61 X 81cm )', '24" X 36" ( 60 X 90cm )'],
    lastSize: '50" X 100" ( 127 X 254cm )',
    frameOptions: ["Rolled Canvas", "Black Frame", "Gold Frame", "Silver Frame", "Wood Frame", "White Frame"],
    styleLine: "Golden blossom tree textured wall decor for warm modern homes.",
    summary: "BGM 010 is a golden blossom tree artwork with textured wall-decor positioning. Source data shows it as a handmade texture product with 16 size options and six finish choices.",
    bestFor: "Entryways, living rooms, bedrooms, dining rooms, and spaces needing warmth or symbolic growth.",
    palette: "Gold, blue-green, cream, and natural accent tones.",
    texture: "Textured blossom details over handmade canvas.",
    composition: "The tree subject gives the piece a clear vertical focal point while the abstract treatment keeps it modern.",
    roomGuide: "Use it where guests first enter or where a room needs a warmer emotional tone than pure abstract geometry.",
    sizeGuide: "For entry consoles, use medium sizes. Above a sofa or dining sideboard, select a wide or large vertical-impact format from the 16 available sizes.",
    stylingTips: ["Gold framing reinforces the blossom highlights.", "Wood framing makes it more natural and less formal.", "Pair with warm lamps, brass hardware, and green plant accents."],
    highlights: ["Tree subject", "Gold accent palette", "16 size options", "17 public review count"],
  },
  {
    slug: "beige-brown-abstract-painting-ll-0409",
    title: "Vibrant Tree Landscape Wall Art #LL 0409",
    sku: "LL 0409",
    price: "From $198.75",
    priceMax: "$2,910.00",
    reviews: "33 reviews",
    image: "/art/p07.jpg",
    imageAlt: "Vitality in Bloom: Vibrant Tree Landscape Wall Art for home decor #LL 0409",
    productType: "abstract",
    tags: ["blue-green", "texture"],
    publishedAt: "2024-02-01",
    imageCount: 7,
    sizeCount: 16,
    firstSizes: ['18" X 24" ( 46 X 61cm )', '21" X 28" ( 53 X 71cm )', '24" X 32" ( 61 X 81cm )', '24" X 36" ( 60 X 90cm )'],
    lastSize: '50" X 100" ( 127 X 254cm )',
    frameOptions: ["Rolled Canvas", "Black Frame", "Gold Frame", "Silver Frame", "Wood Frame", "White Frame"],
    styleLine: "Large tree landscape abstract painting with bright natural energy.",
    summary: "LL 0409 is listed as large tree wall decor and abstract painting wall art. Source data shows an abstract product type, 16 size choices, and a strong public review count.",
    bestFor: "Family rooms, cheerful living rooms, breakfast areas, offices, and spaces needing energetic color.",
    palette: "Vibrant tree colors with green, warm, and natural landscape notes.",
    texture: "Handmade paint on high-quality linen canvas, with framed or rolled options.",
    composition: "The tree landscape format gives a recognizable subject while retaining abstract brush movement.",
    roomGuide: "Use this product when a room feels too neutral or flat and needs color that still connects to nature.",
    sizeGuide: "Small sizes work for reading nooks. Use 36 x 48 inches or larger where the tree needs to carry the room visually.",
    stylingTips: ["Repeat one accent color from the artwork in pillows or ceramics.", "Choose a wood frame for a natural landscape feel.", "Keep surrounding wall decor minimal because the artwork already has strong color."],
    highlights: ["Abstract tree landscape", "33 public review count", "16 size options", "Free shipping"],
  },
  {
    slug: "beige-minimalist-abstract-painting-avg-003",
    title: "Beige Minimalist Abstract Painting #AVG 003",
    sku: "AVG 003",
    price: "From $198.75",
    priceMax: "$2,643.75",
    reviews: "36 reviews",
    image: "/art/p08.jpg",
    imageAlt: "Whispering Waves: Wabi Sabi Art Beige 3D Minimalist Wall Sculpture",
    productType: "texture",
    tags: ["beige-brown", "texture", "wabi-sabi"],
    publishedAt: "2024-02-28",
    imageCount: 11,
    sizeCount: 13,
    firstSizes: ['18" X 24" ( 46 X 61cm )', '21" X 28" ( 53 X 71cm )', '24" X 32" ( 61 X 81cm )', '24" X 36" ( 60 X 90cm )'],
    lastSize: '60" X 80" ( 152 X 202cm )',
    frameOptions: ["Rolled Canvas", "Black Frame", "Gold Frame", "Silver Frame", "Wood Frame", "White Frame"],
    styleLine: "Beige white 3D minimalist wabi-sabi wall sculpture effect.",
    summary: "AVG 003 is a beige minimalist abstract painting with wabi-sabi tags in the source data. It includes 11 product images, 13 size options, and a creation time listed as about 1-2 weeks.",
    bestFor: "Wabi-sabi rooms, minimalist bedrooms, meditation spaces, luxury neutral interiors, and quiet gallery walls.",
    palette: "Beige, white, cream, and soft shadow.",
    texture: "3D minimalist texture with a wall-sculpture feel.",
    composition: "The soft relief-like surface creates depth through shadow rather than high contrast color.",
    roomGuide: "Use this in rooms where texture matters more than color: limewash walls, linen bedding, stone tables, and low-profile furniture.",
    sizeGuide: "Because the palette is quiet, choose a larger size than you would for a high-contrast piece. The 60 x 80 inch option is useful for large calm walls.",
    stylingTips: ["Use warm, angled lighting to reveal the 3D texture.", "Pair with travertine, oak, wool, linen, and matte ceramics.", "Avoid busy patterned textiles nearby; they compete with the subtle relief."],
    highlights: ["Wabi-sabi tag", "11 source images", "13 size options", "36 public review count"],
  },
  {
    slug: "black-minimalist-abstract-painting-avg-012",
    title: "Black Minimalist Abstract Painting #AVG 012",
    sku: "AVG 012",
    price: "From $233.75",
    priceMax: "$3,498.75",
    reviews: "24 reviews",
    image: "/art/p09.jpg",
    imageAlt: "Nordic Sophistication: Oversize Black Minimalist Artwork for a Stylish Apartment #AVG 012",
    productType: "texture",
    tags: ["black", "texture"],
    publishedAt: "2024-02-21",
    imageCount: 6,
    sizeCount: 11,
    firstSizes: ['24" X 24" ( 61 X 61cm )', '30" X 30" ( 76 X 76cm )', '36" X 36" ( 91 X 91cm )', '40" X 40" ( 101 X 101cm )'],
    lastSize: '80" X 80" ( 202 X 202cm )',
    frameOptions: ["Rolled Canvas", "Black Frame", "Gold Frame", "Silver Frame", "Wood Frame", "White Frame"],
    styleLine: "Oversize black 3D minimalist texture artwork for stylish apartments.",
    summary: "AVG 012 is a black minimalist abstract painting. Source data describes it as black 3D minimalist texture contemporary wall art, with square sizes from 24 x 24 to 80 x 80 inches.",
    bestFor: "Apartments, lofts, media rooms, monochrome interiors, and modern rooms that need a sharp focal point.",
    palette: "Black, charcoal, white, and subtle neutral texture.",
    texture: "3D minimalist texture with a contemporary wall-art finish.",
    composition: "The square format creates a strong centered statement, useful when furniture and architecture are linear.",
    roomGuide: "Use this when a room needs weight, contrast, and a gallery-like mood. It pairs especially well with black lighting or window frames.",
    sizeGuide: "Because this product is square, match it to square wall zones or use it above symmetrical furniture. Larger sizes create a bolder architectural effect.",
    stylingTips: ["A black frame creates a seamless sculptural look.", "A white frame adds contrast and makes the piece more gallery-like.", "Use with low, warm lighting to make the black texture readable."],
    highlights: ["Square format", "Black 3D minimalist style", "11 size options", "24 public review count"],
  },
  {
    slug: "large-black-white-abstract-textured-canvas-art-bm-092",
    title: "Large Black & White Abstract Textured Canvas Art #BM 092",
    sku: "BM 092",
    price: "From $198.75",
    priceMax: "$2,643.75",
    reviews: "4 reviews",
    image: "/art/p10.jpg",
    imageAlt: "Large Black & White Abstract Textured Canvas Art #BM 092",
    productType: "texture",
    tags: ["black", "texture"],
    publishedAt: "2024-10-24",
    imageCount: 9,
    sizeCount: 13,
    firstSizes: ['18" X 24" ( 46 X 61cm )', '21" X 28" ( 53 X 71cm )', '24" X 32" ( 61 X 81cm )', '24" X 36" ( 60 X 90cm )'],
    lastSize: '60" X 80" ( 152 X 202cm )',
    frameOptions: ["Rolled Canvas", "Black Frame", "Gold Frame", "Silver Frame", "Wood Frame", "White Frame"],
    styleLine: "Large black and white textured canvas for contemporary walls.",
    summary: "BM 092 is a large black and white abstract textured canvas. The source product identifies it as black 3D minimalist texture contemporary wall art with 13 size choices.",
    bestFor: "Modern living rooms, office walls, high-contrast bedrooms, and spaces with black-and-white decor.",
    palette: "Black, white, gray, and neutral shadow.",
    texture: "Hand-applied texture over linen canvas using professional oil or acrylic paint.",
    composition: "The black-and-white contrast creates a clearer graphic statement than the softer beige or blue-green works.",
    roomGuide: "Use this to tie together black hardware, white walls, gray rugs, marble, or monochrome furniture.",
    sizeGuide: "Choose medium sizes for side walls and 40 x 54 inches or larger for main furniture walls. The 60 x 80 inch option suits tall statement areas.",
    stylingTips: ["Keep nearby art minimal to avoid visual clutter.", "Use black or silver framing for a crisp modern finish.", "Pair with sculptural lamps, marble, chrome, or matte black accents."],
    highlights: ["Black-white palette", "9 source images", "13 size options", "Made-to-order"],
  },
  {
    slug: "black-white-abstract-painting-set-of-2-cxa-013",
    title: "Black & White Abstract Painting SET OF 2 #CXA 013",
    sku: "CXA 013",
    price: "From $261.25",
    priceMax: "$3,968.75",
    reviews: "11 reviews",
    image: "/art/p11.jpg",
    imageAlt: "Elegant Dichotomy: Contemporary Black and White Abstract Diptych #LL 013",
    productType: "combine",
    tags: ["abstract-black", "abstract-white", "black", "combine", "wabi-sabi", "white"],
    publishedAt: "2023-12-28",
    imageCount: 7,
    sizeCount: 15,
    firstSizes: ['2P 36" X 24"  ( Each 18" X 24" )', '2P 42" X 28"  ( Each 21" X 28" )', '2P 48" X 32"  ( Each 24" X 32" )', '2P 48" X 36"  ( Each 24" X 36" )'],
    lastSize: '2P 120" X 90"  ( Each 60" X 90" )',
    frameOptions: ["Rolled Canvas", "Black Frame", "Gold Frame", "Silver Frame", "Wood Frame", "White Frame"],
    styleLine: "Contemporary black and white abstract diptych.",
    summary: "CXA 013 is a black and white abstract painting set of 2. Source data identifies it as a combine product with 15 paired sizes and tags including black, white, combine, and wabi-sabi.",
    bestFor: "Wide living room walls, master bedrooms, offices, and spaces needing balanced black-and-white art.",
    palette: "Black, white, off-white, and gray.",
    texture: "Handmade abstract surface on two canvases, available rolled or framed.",
    composition: "The diptych format allows the two canvases to balance each other while covering more wall width than a single piece.",
    roomGuide: "Use this above long furniture when one centered canvas would leave too much empty wall on both sides.",
    sizeGuide: "Measure the total pair width and include the gap between panels. The largest 2P 120 x 90 inch size works for oversized walls and open-plan rooms.",
    stylingTips: ["Keep the gap between panels even and intentional.", "Black framing gives a strong architectural look.", "Use white or wood framing to soften the diptych for lighter interiors."],
    highlights: ["Set of 2", "15 paired sizes", "Wabi-sabi tag", "11 public review count"],
  },
  {
    slug: "blue-green-minimalist-abstract-painting-bgm-007",
    title: "Blue & Green Minimalist Abstract Painting #BGM 007",
    sku: "BGM 007",
    price: "From $198.75",
    priceMax: "$2,910.00",
    reviews: "7 reviews",
    image: "/art/p12.jpg",
    imageAlt: "Textured Forest Landscape Painting | Misty Green Woods Canvas Art #BGM 007",
    productType: "texture",
    tags: ["blue-green"],
    publishedAt: "2024-03-24",
    imageCount: 8,
    sizeCount: 16,
    firstSizes: ['18" X 24" ( 46 X 61cm )', '21" X 28" ( 53 X 71cm )', '24" X 32" ( 61 X 81cm )', '24" X 36" ( 60 X 90cm )'],
    lastSize: '50" X 100" ( 127 X 254cm )',
    frameOptions: ["Rolled Canvas", "Black Frame", "Gold Frame", "Silver Frame", "Wood Frame", "White Frame"],
    styleLine: "Misty green forest landscape texture painting.",
    summary: "BGM 007 is a blue-green minimalist abstract painting with source alt text describing a textured forest landscape and misty green woods canvas art. It offers 16 sizes and six finish options.",
    bestFor: "Bedrooms, reading rooms, wellness spaces, offices, and calm living rooms.",
    palette: "Misty green, blue-green, white, and soft forest tones.",
    texture: "Handmade canvas texture with an atmospheric landscape impression.",
    composition: "The forest reference gives depth and calm while remaining abstract enough for modern interiors.",
    roomGuide: "Use this piece when you want a nature mood without a literal scenic painting. It works especially well in rooms with plants or green textiles.",
    sizeGuide: "Smaller formats suit side walls and quiet corners. Larger 40 x 80 or 50 x 100 inch formats create a calming feature wall.",
    stylingTips: ["Pair with natural wood, linen bedding, and matte ceramic decor.", "A wood frame supports the forest mood; a white frame keeps it fresh and minimal.", "Use near warm lighting to prevent the green palette from feeling cold."],
    highlights: ["Forest landscape mood", "8 source images", "16 size options", "Custom size available"],
  },
];

export function getProductBySlug(slug: string) {
  return products.find((product) => product.slug === slug);
}
